import Foundation

/// Human-readable descriptions for known Apple system services.
/// Displayed in the job detail Identity section for system domains.
/// Every entry verified against actual plists on macOS 26.
public struct AppleServiceInfo: Sendable {

    /// Returns a description for a known Apple service label, or nil if unknown.
    public static func description(for label: String) -> String? {
        knownServices[label]
    }

    private static let knownServices: [String: String] = [
        "bootps": "Provides BOOTP and DHCP server for network boot services",
        "com.apple.AMPArtworkAgent": "Fetches and caches album artwork for Apple Music",
        "com.apple.AMPDeviceDiscoveryAgent": "Discovers nearby devices for Apple Music syncing",
        "com.apple.AMPDevicesAgent": "Apple Music and media device sync agent",
        "com.apple.AMPLibraryAgent": "Manages the Apple Music and iTunes library database",
        "com.apple.AMPSystemPlayerAgent": "Handles system-level music playback and Now Playing info",
        "com.apple.AOSHeartbeat": "Sends periodic heartbeats to Apple cloud services",
        "com.apple.AOSPushRelay": "Relays push notifications from Apple cloud services",
        "com.apple.AccessibilityUIServer": "Handles core accessibility UI interactions and assistive technology",
        "com.apple.AccessibilityVisualsAgent": "Manages visual accessibility overlays and display adjustments",
        "com.apple.AddressBook.AssistantService": "Provides Siri integration for Contacts lookups",
        "com.apple.AddressBook.SourceSync": "Syncs contacts across accounts and sources",
        "com.apple.AddressBook.abd": "Manages Contacts database operations and storage",
        "com.apple.AirPlayUIAgent": "Shows AirPlay mirroring and streaming UI controls",
        "com.apple.AirPlayXPCHelper": "Handles privileged AirPlay streaming operations",
        "com.apple.AirPortBaseStationAgent": "Manages and monitors AirPort base station configuration",
        "com.apple.AppSSOAgent": "Handles enterprise single sign-on authentication prompts",
        "com.apple.AppSSOAgent.login": "Manages single sign-on during the login window",
        "com.apple.AppSSODaemon": "Provides extensible single sign-on services for apps",
        "com.apple.AppleCredentialManagerDaemon": "Stores and manages authentication credentials securely",
        "com.apple.AppleQEMUGuestAgent": "Provides guest integration for QEMU virtual machines",
        "com.apple.AquaAppearanceHelper.agent": "Applies system appearance and theme changes",
        "com.apple.AskPermissionUI": "Shows Screen Time permission request dialogs",
        "com.apple.AssetCache.agent": "Provides user interface for Content Caching settings",
        "com.apple.AssetCache.builtin": "Caches Apple software updates and iCloud content locally",
        "com.apple.AssetCacheLocatorService": "Discovers nearby content caching servers on the network",
        "com.apple.AssetCacheManagerService": "Controls content caching server configuration and status",
        "com.apple.AssetCacheTetheratorService": "Shares cached content with tethered iOS devices",
        "com.apple.AssistiveControl": "Enables switch control and assistive input devices",
        "com.apple.AuthenticationServicesCore.AuthenticationServicesAgent": "Handles passkey and web authentication sign-in prompts",
        "com.apple.AutoFillPanel": "Shows password and credential AutoFill suggestions",
        "com.apple.BTServer.le": "Handles Bluetooth Low Energy connections and services",
        "com.apple.BTServerAgent.le": "Manages user-level Bluetooth Low Energy interactions",
        "com.apple.BiomeAgent": "Indexes user activity data for on-device intelligence",
        "com.apple.BlueTool": "Provides low-level Bluetooth hardware diagnostic utilities",
        "com.apple.CSCSupportd": "Provides customer support connectivity and diagnostics",
        "com.apple.CallHistoryPluginHelper": "Processes call history data for Spotlight and Siri",
        "com.apple.CallHistorySyncHelper": "Syncs call history records across iCloud devices",
        "com.apple.CloudSettingsSyncAgent": "Syncs system settings and preferences via iCloud",
        "com.apple.CommCenter-osx": "Manages cellular modem and telephony on supported Macs",
        "com.apple.ContainerMigrationService": "Migrates app sandbox containers during system upgrades",
        "com.apple.ContextStoreAgent": "Stores user context signals for on-device intelligence",
        "com.apple.CoreAuthentication.agent": "Handles user authentication prompts and biometric checks",
        "com.apple.CoreAuthentication.daemon": "Provides system-level authentication and credential services",
        "com.apple.CoreLocationAgent": "Shows location access prompts and status indicators",
        "com.apple.CrashReporterSupportHelper": "Gathers system info for crash reports and diagnostics",
        "com.apple.CryptoTokenKit.ahp": "Manages smart card and security token hardware access",
        "com.apple.CryptoTokenKit.ahp.agent": "Handles user-level smart card authentication prompts",
        "com.apple.DataDetectorsLocalSources": "Detects dates, addresses, and phone numbers in local content",
        "com.apple.DataDetectorsSourceAccess": "Provides data detector results to apps requesting them",
        "com.apple.DesktopServicesHelper": "Manages Desktop, Finder metadata, and .DS_Store files",
        "com.apple.DiagnosticsReporter": "Generates and submits system diagnostic reports to Apple",
        "com.apple.DictationIM": "Processes voice input for system-wide Dictation",
        "com.apple.DiskArbitrationAgent": "Notifies apps when disks are mounted or unmounted",
        "com.apple.Dock": "Runs the Dock, app launcher, and window management bar",
        "com.apple.DumpGPURestart": "Collects GPU crash data when the graphics processor resets",
        "com.apple.DumpPanic": "Saves kernel panic logs after a system crash",
        "com.apple.DumpPanic.Accessory": "Saves crash logs from connected accessories",
        "com.apple.DwellControl": "Enables accessibility dwell-click control for pointer input",
        "com.apple.EscrowSecurityAlert": "Alerts when iCloud Keychain escrow needs attention",
        "com.apple.ExpansionSlotNotification": "Notifies about expansion slot and card changes",
        "com.apple.FamilyControlsAgent": "Shows Screen Time and parental control prompts to users",
        "com.apple.FeatureAccessAgent": "Controls access to features based on parental controls",
        "com.apple.FileCoordination": "Coordinates safe file access between multiple apps",
        "com.apple.FileProvider": "Enables cloud storage providers to integrate with Finder",
        "com.apple.FilesystemUI": "Shows disk and file system alerts and prompts",
        "com.apple.Finder": "Runs Finder, the file manager and desktop environment",
        "com.apple.FolderActionsDispatcher": "Triggers Folder Actions scripts when folder contents change",
        "com.apple.FollowUpUI": "Shows follow-up notifications for incomplete setup steps",
        "com.apple.FontRegistryUIAgent": "Prompts user when apps request font installation",
        "com.apple.FontValidator": "Validates font files for errors and compatibility",
        "com.apple.FontWorker": "Processes font rendering and glyph operations",
        "com.apple.GSSCred": "Kerberos credential management",
        "com.apple.GameController.gamecontrolleragentd": "Manages game controller connections and input for apps",
        "com.apple.GameController.gamecontrollerd": "Provides system-level game controller hardware support",
        "com.apple.GameOverlayUI": "Shows Game Center overlay UI during gameplay",
        "com.apple.GamePolicyAgent": "Enforces Screen Time gaming restrictions for users",
        "com.apple.IFCStart": "Initializes Internet File Caching at startup",
        "com.apple.IOAccelMemoryInfoCollector": "Collects GPU memory usage statistics",
        "com.apple.IOUIAgent": "Shows hardware-related alerts and user prompts",
        "com.apple.InstallerDiagnostics.installerdiagd": "Diagnoses and logs software installation failures",
        "com.apple.InstallerDiagnostics.installerdiagwatcher": "Monitors installations for diagnostic data collection",
        "com.apple.InstallerProgress": "Displays installation progress bars and status UI",
        "com.apple.Kerberos.digest-service": "Provides HTTP Digest authentication via Kerberos",
        "com.apple.Kerberos.kadmind": "Administers the Kerberos authentication database",
        "com.apple.Kerberos.kcm": "Manages Kerberos credential cache for single sign-on",
        "com.apple.Kerberos.kdc": "Runs the Kerberos Key Distribution Center for authentication",
        "com.apple.Kerberos.kpasswdd": "Handles Kerberos password change requests",
        "com.apple.KernelEventAgent": "Responds to kernel events like disk-full and power changes",
        "com.apple.KeyboardAccessAgent": "Manages Full Keyboard Access accessibility navigation",
        "com.apple.LinkedNotesUIService": "Shows Quick Note link suggestions from highlighted content",
        "com.apple.LocalAuthentication.UIAgent": "Shows Touch ID and password authentication prompts",
        "com.apple.MENotificationAgent": "Delivers Mail extension notification alerts",
        "com.apple.MTLAssetUpgraderD": "Upgrades Metal GPU shader caches for new hardware or drivers",
        "com.apple.ManagedClient": "MDM managed client — enforces enterprise device management policies",
        "com.apple.ManagedClient.enroll": "Enrolls the Mac in a device management profile",
        "com.apple.ManagedClient.mechanism": "Applies managed client login policies during authentication",
        "com.apple.ManagedClient.startup": "Applies managed configuration profiles at system startup",
        "com.apple.ManagedClientAgent.agent": "Enforces MDM configuration profiles for the current user",
        "com.apple.ManagedClientAgent.enrollagent": "Handles user-level MDM enrollment prompts",
        "com.apple.ManagedSettingsAgent": "Enforces Screen Time and parental control restrictions",
        "com.apple.Maps.mapssyncd": "Syncs Maps favorites and collections across your devices",
        "com.apple.Maps.pushdaemon": "Receives push notifications for Maps transit and ETA alerts",
        "com.apple.MemorySlotNotification": "Alerts about memory module changes or hardware issues",
        "com.apple.MobileAccessoryUpdater.fudHelperAgent": "Updates firmware on connected Apple accessories",
        "com.apple.MobileFileIntegrity": "Verifies code signatures and enforces app integrity checks",
        "com.apple.ModelCatalogAgent": "Provides user-level access to on-device ML model catalog",
        "com.apple.NVMeAgent": "Monitors NVMe storage drive health and performance",
        "com.apple.NetworkLinkConditioner": "Simulates network conditions for app testing and development",
        "com.apple.NetworkSharing": "Manages Internet Sharing and network sharing services",
        "com.apple.NowPlayingTouchUI": "Shows Now Playing controls on Touch Bar or Control Strip",
        "com.apple.ODSAgent": "Manages Open Directory shared contacts and directory lookups",
        "com.apple.OSDUIHelper": "Displays on-screen overlays for volume, brightness, and keyboard",
        "com.apple.PIPAgent": "Provides Picture-in-Picture floating video window support",
        "com.apple.PackageUIKit.InstallStatus": "Shows installation progress for macOS software packages",
        "com.apple.PasswordService": "Provides password authentication for Open Directory services",
        "com.apple.PerfPowerServices": "Monitors system performance and power usage for optimization",
        "com.apple.PerfPowerServicesExtended": "Collects extended performance and power diagnostics data",
        "com.apple.PosterBoard": "Manages Lock Screen customization and widget display",
        "com.apple.PowerUIAgent": "Displays battery status, power alerts, and charging notifications",
        "com.apple.RFBEventHelper": "Processes remote input events for Screen Sharing VNC connections",
        "com.apple.RapportUIAgent": "Shows UI prompts for nearby Apple device connections",
        "com.apple.RemoteDesktop": "Enables Apple Remote Desktop screen sharing and management",
        "com.apple.RemoteDesktop.PrivilegeProxy": "Handles privileged operations for Apple Remote Desktop access",
        "com.apple.RemoteManagementAgent": "Applies remote management policies from your IT administrator",
        "com.apple.ReportCrash": "Crash report generator — creates .ips files after app crashes",
        "com.apple.ReportCrash.Root": "Captures crash reports for system processes running as root",
        "com.apple.ReportGPURestart": "Reports GPU crash and restart events for diagnostics",
        "com.apple.ReportMemoryException": "Reports memory limit violations for diagnostics",
        "com.apple.ReportSystemMemory": "Reports system memory pressure events for diagnostics",
        "com.apple.SCHelper": "Applies privileged system network configuration changes",
        "com.apple.SSInvitationAgent": "Handles incoming screen sharing invitation requests",
        "com.apple.Safari.History": "Maintains and syncs Safari browsing history",
        "com.apple.Safari.PasswordBreachAgent": "Alerts you when saved passwords appear in data breaches",
        "com.apple.Safari.SafeBrowsing.Service": "Checks websites against known malicious site databases",
        "com.apple.SafariBookmarksSyncAgent": "Syncs Safari bookmarks across your iCloud devices",
        "com.apple.SafariHistoryServiceAgent": "Manages Safari history database and search indexing",
        "com.apple.SafariLaunchAgent": "Handles Safari background tasks and extension updates",
        "com.apple.SafariNotificationAgent": "Delivers website push notifications from Safari",
        "com.apple.SafeEjectGPUAgent": "Helps safely disconnect external GPUs before removal",
        "com.apple.SafeEjectGPUStartupDaemon": "Manages external GPU connections during startup and shutdown",
        "com.apple.ScreenReaderUIServer": "Renders VoiceOver accessibility overlay and spoken interface",
        "com.apple.ScreenTimeAgent": "Tracks app usage and enforces Screen Time limits",
        "com.apple.ScriptMenuApp": "Shows the system Scripts menu in the menu bar",
        "com.apple.SecureBackupDaemon": "Handles encrypted iCloud Keychain backup and recovery",
        "com.apple.ServicesUIAgent": "Displays UI for system Services menu actions",
        "com.apple.Siri.agent": "Runs the Siri voice assistant and handles requests",
        "com.apple.SiriTTSTrainingAgent": "Trains and optimizes Siri text-to-speech voice models",
        "com.apple.SoftwareUpdateNotificationManager": "Displays notifications about available macOS updates",
        "com.apple.SpacesTouchBarAgent": "Shows Mission Control Spaces controls on the Touch Bar",
        "com.apple.Spotlight": "Indexes files and content for fast system-wide search",
        "com.apple.StatusKitAgent": "Manages user status sharing across system apps",
        "com.apple.StorageManagement.Service": "Provides storage optimization recommendations and cleanup tools",
        "com.apple.StorageManagementUIHelper": "Displays the storage management interface in System Settings",
        "com.apple.SubmitDiagInfo": "Sends anonymized crash and diagnostic reports to Apple",
        "com.apple.SystemUIServer": "Hosts menu bar extras and system UI elements",
        "com.apple.TMHelperAgent": "Assists Time Machine with backup scheduling and status",
        "com.apple.TextInputMenuAgent": "Manages the input source menu in the menu bar",
        "com.apple.TextInputSwitcher": "Handles switching between keyboard input sources and languages",
        "com.apple.ThreadCommissionerService": "Commissions and configures Thread smart home network devices",
        "com.apple.TrustEvaluationAgent": "Performs certificate chain trust evaluation for the user",
        "com.apple.TrustEvaluationAgent.system": "Performs system-level certificate chain trust evaluation",
        "com.apple.UpdateSettings": "Manages automatic software update preferences and scheduling",
        "com.apple.UsageTrackingAgent": "Tracks app usage data for Screen Time reporting",
        "com.apple.UserEventAgent-Aqua": "Processes user-level system events in the desktop session",
        "com.apple.UserEventAgent-CryptexContainer": "Handles user events within cryptex container contexts",
        "com.apple.UserEventAgent-LoginWindow": "Processes system events at the login window",
        "com.apple.UserEventAgent-System": "Processes system-wide events for all users",
        "com.apple.UserNotificationCenter": "Displays legacy notification dialogs to the user",
        "com.apple.UserNotificationCenterAgent": "Manages and presents user notification alerts",
        "com.apple.UserNotificationCenterAgent-LoginWindow": "Displays notification alerts at the login window",
        "com.apple.UserPictureSyncAgent": "Syncs your user profile picture across Apple devices",
        "com.apple.Virtualization.AppleVirtualPlatformHIDBridge": "Bridges HID input devices to Apple virtual machines",
        "com.apple.VoiceOver": "Provides spoken screen reader accessibility for vision needs",
        "com.apple.WindowManager": "Provides window tiling, Stage Manager, and window management",
        "com.apple.WindowServer": "Composites all windows to the display and routes input events",
        "com.apple.WirelessRadioManager-osx": "Manages Bluetooth and wireless radio hardware state",
        "com.apple.accessibility.AXVisualSupportAgent": "Provides visual accessibility features like color filters and zoom",
        "com.apple.accessibility.LiveTranscriptionAgent": "Provides real-time live captions for audio content",
        "com.apple.accessibility.MotionTrackingAgent": "Tracks head and body motion for accessibility controls",
        "com.apple.accessibility.axassetsd": "Manages accessibility asset resources and downloads",
        "com.apple.accessibility.dfrhud": "Shows accessibility controls on the Touch Bar display",
        "com.apple.accessibility.heard": "Supports hearing accessibility features and sound recognition",
        "com.apple.accessoryd": "Communicates with connected MFi accessories and peripherals",
        "com.apple.accessorysensormgrd": "Manages sensor data from connected accessories",
        "com.apple.accessoryupdaterd": "Handles firmware updates for connected Apple accessories",
        "com.apple.accountsd": "Account management daemon for Internet Accounts",
        "com.apple.adid": "Manages the advertising identifier for privacy controls",
        "com.apple.afpfs_afpLoad": "Mounts Apple Filing Protocol network shares",
        "com.apple.afpfs_checkafp": "Monitors health of mounted AFP network shares",
        "com.apple.airportd": "Wi-Fi management daemon",
        "com.apple.akd": "Handles Apple ID authentication and AuthKit operations",
        "com.apple.alf.agent": "Manages the Application Layer Firewall rules",
        "com.apple.alf.useragent": "Shows firewall alerts and connection prompts to the user",
        "com.apple.alwaysonexclavesd": "Manages always-on Secure Enclave processes",
        "com.apple.amp.mediasharingd": "Shares media libraries over the local network",
        "com.apple.amsaccountsd": "Manages App Store and media account sessions",
        "com.apple.amsengagementd": "Tracks App Store engagement and personalized recommendations",
        "com.apple.amsondevicestoraged": "Manages on-device App Store data storage",
        "com.apple.analyticsagent": "Collects and submits analytics and diagnostics data",
        "com.apple.analyticsd": "Analytics daemon — collects and reports diagnostic data to Apple",
        "com.apple.aned": "Manages the Apple Neural Engine for machine learning tasks",
        "com.apple.aneuserd": "Handles user-space Apple Neural Engine requests",
        "com.apple.aonsensed": "Processes always-on sensor data for ambient features",
        "com.apple.ap.adprivacyd": "Enforces ad attribution privacy protections",
        "com.apple.ap.promotedcontentd": "Manages personalized content and App Store ad delivery",
        "com.apple.apfsd": "Manages Apple File System (APFS) volumes and operations",
        "com.apple.apfsuseragent": "Handles user-facing APFS volume prompts and notifications",
        "com.apple.appinstalld": "Installs, updates, and removes applications",
        "com.apple.appleaccountd": "Manages Apple Account sign-in and credential storage",
        "com.apple.appleh13camerad": "Operates the built-in camera on Apple Silicon M1 Macs",
        "com.apple.appleh16camerad": "Operates the built-in camera on Apple Silicon M4 Macs",
        "com.apple.appleidsetupd": "Guides Apple ID setup and configuration during onboarding",
        "com.apple.applekeystored": "Manages the secure keychain and cryptographic key storage",
        "com.apple.appleseed.fbahelperd": "Supports AppleSeed beta feedback and bug reporting",
        "com.apple.appleseed.seedusaged": "Tracks beta program enrollment and seed build usage",
        "com.apple.appleseed.seedusaged.postinstall": "Runs AppleSeed usage tasks after system updates",
        "com.apple.applespell": "Provides system-wide spell checking services",
        "com.apple.applessdstatistics": "Collects SSD health and storage statistics",
        "com.apple.appplaceholdersyncd": "Syncs app placeholder icons across devices",
        "com.apple.appsleepd": "Manages app nap and background app power savings",
        "com.apple.appstoreagent": "Handles App Store download and update operations",
        "com.apple.appstorecomponentsd": "Manages App Store component and plugin delivery",
        "com.apple.appstored": "Manages App Store catalog, purchases, and subscriptions",
        "com.apple.apsd": "Apple Push Notification Service — maintains persistent server connection",
        "com.apple.arkitd": "Provides ARKit augmented reality processing services",
        "com.apple.askpermissiond": "Processes Screen Time permission requests from children",
        "com.apple.asktod": "Manages Ask to Buy purchase approval workflows",
        "com.apple.aslmanager": "Rotates and compresses Apple System Log files",
        "com.apple.asr": "Performs Apple Software Restore disk imaging operations",
        "com.apple.assessmentagent": "Manages Gatekeeper app security assessments",
        "com.apple.assetsubscriptiond": "Manages subscriptions for downloadable system assets",
        "com.apple.assistant_cdmd": "Handles Siri voice command processing and dispatch",
        "com.apple.assistant_service": "Provides core Siri assistant request handling",
        "com.apple.assistantd": "Runs the main Siri assistant background service",
        "com.apple.atrun": "Executes scheduled commands from the at(1) job queue",
        "com.apple.attentionawarenessd": "Detects user attention and presence via camera sensors",
        "com.apple.audio.AudioComponentRegistrar": "Registers user-installed audio plug-ins and components",
        "com.apple.audio.AudioComponentRegistrar.daemon": "Registers system-level audio plug-ins and components",
        "com.apple.audio.coreaudiod": "Core Audio daemon — manages all audio input/output and routing",
        "com.apple.audio.micactivityd": "Tracks and displays microphone usage by applications",
        "com.apple.audio.systemsoundserverd": "Plays system alert sounds and UI sound effects",
        "com.apple.audioanalyticsd": "Analyzes ambient sounds for Sound Recognition alerts",
        "com.apple.audiomxd": "Manages audio mixing and routing between applications",
        "com.apple.auditd": "Records security audit logs for system events",
        "com.apple.autofsd": "Manages the automounter configuration and triggers",
        "com.apple.automountd": "Automatically mounts network file systems on access",
        "com.apple.avatarsd": "Creates and manages Memoji and avatar assets",
        "com.apple.avbdeviced": "Manages Audio Video Bridging network streaming devices",
        "com.apple.avconferenced": "Handles FaceTime and video conferencing media streams",
        "com.apple.backgroundassets.user": "Downloads app assets in the background before first launch",
        "com.apple.backgroundtaskmanagement.agent": "Schedules and manages background tasks for applications",
        "com.apple.backgroundtaskmanagementd": "Background Task Management — controls which apps run in background",
        "com.apple.backupd": "Runs Time Machine backups on schedule",
        "com.apple.backupd-helper": "Assists Time Machine with backup snapshot operations",
        "com.apple.betaenrollmentagent": "Shows beta program enrollment UI and notifications",
        "com.apple.betaenrollmentd": "Manages macOS beta software update enrollment",
        "com.apple.biomed": "Stores and processes biometric and health-related data",
        "com.apple.biomesyncd": "Syncs Biome activity data across user devices",
        "com.apple.biometrickitd": "Manages Touch ID and biometric authentication hardware",
        "com.apple.bird": "iCloud Drive file coordinator daemon",
        "com.apple.bluetoothUIServer": "Shows Bluetooth pairing dialogs and setup assistant",
        "com.apple.bluetoothaudiod": "Routes audio to and from Bluetooth headphones and speakers",
        "com.apple.bluetoothd": "Manages all Bluetooth connections and device pairing",
        "com.apple.bluetoothuiservice": "Provides Bluetooth UI elements and system menu controls",
        "com.apple.bluetoothuserd": "Handles per-user Bluetooth preferences and device state",
        "com.apple.bookassetd": "Downloads and manages Apple Books content and assets",
        "com.apple.bookdatastored": "Stores reading progress and bookmarks for Apple Books",
        "com.apple.bootinstalld": "Installs boot components during macOS updates",
        "com.apple.bosreporter": "Reports BridgeOS status from the Apple T-series chip",
        "com.apple.boswatcher": "Monitors BridgeOS firmware state on the T-series chip",
        "com.apple.bridgeOSUpdateProxy": "Proxies firmware updates to the T-series security chip",
        "com.apple.bsd.dirhelper": "Creates and cleans per-user temporary directories",
        "com.apple.btsa": "Manages Bluetooth Smart Accessory communication",
        "com.apple.businessservicesd": "Supports Apple Business features and managed accounts",
        "com.apple.cache_delete": "Frees disk space by purging expendable cached data",
        "com.apple.calaccessd": "Controls Calendar database access and permissions",
        "com.apple.calendar.CalendarAgentBookmarkMigrationService": "Migrates Calendar bookmarks during system upgrades",
        "com.apple.callhistoryd": "Stores and syncs phone and FaceTime call history",
        "com.apple.callintelligenced": "Identifies and screens spam and unknown callers",
        "com.apple.cameracaptured": "Manages camera capture sessions and frame processing",
        "com.apple.captiveagent": "Detects captive Wi-Fi portals and shows login pages",
        "com.apple.cdpd": "Manages Continuity and device pairing over iCloud",
        "com.apple.cfnetwork.AuthBrokerAgent": "Brokers HTTP authentication credentials across apps",
        "com.apple.cfnetwork.cfnetworkagent": "Handles system-level network configuration and proxies",
        "com.apple.cfprefsd.xpc.agent": "Manages per-user app preferences and defaults",
        "com.apple.cfprefsd.xpc.daemon": "Manages system-wide preferences and defaults storage",
        "com.apple.chronod": "Schedules and triggers watch-face complications and widgets",
        "com.apple.ciphermld": "Processes encrypted machine learning models on-device",
        "com.apple.ckdiscretionaryd": "Batches CloudKit sync operations for energy efficiency",
        "com.apple.cloudd": "CloudKit daemon — syncs app data with iCloud",
        "com.apple.cloudpaird": "Cloud pairing daemon for device-to-device iCloud sync",
        "com.apple.cloudphotod": "Syncs photos and videos with iCloud Photo Library",
        "com.apple.cmfsyncagent": "Syncs configuration management framework data",
        "com.apple.cmio.ContinuityCaptureAgent": "Enables iPhone as a webcam via Continuity Camera",
        "com.apple.cmio.LaunchCMIOUserExtensionsAgent": "Loads user-installed camera extensions and virtual cameras",
        "com.apple.cmio.VDCAssistant": "Manages built-in and external video capture devices",
        "com.apple.cmio.iOSScreenCaptureAssistant": "Captures iOS device screens over USB for QuickTime",
        "com.apple.cmio.registerassistantservice": "Registers available camera devices with the system",
        "com.apple.cmio.uvcassistantextension": "Supports USB Video Class webcams and capture devices",
        "com.apple.cmio.videodriverkithostextension": "Hosts DriverKit-based video capture device extensions",
        "com.apple.colorsync.displayservices": "ColorSync display calibration service",
        "com.apple.colorsync.useragent": "Manages per-user color profile preferences",
        "com.apple.colorsyncd": "Calibrates display color profiles for accurate rendering",
        "com.apple.commerce": "Handles in-app purchases and App Store transactions",
        "com.apple.communicationtrustd": "Evaluates message trust and flags unwanted communications",
        "com.apple.companiond": "Bridges communication between Mac and paired Apple Watch",
        "com.apple.configd": "System configuration daemon — manages network settings and dynamic store",
        "com.apple.configureLocalKDC": "Sets up the local Kerberos authentication server",
        "com.apple.contacts.donation-agent": "Shares contact interaction data with Siri suggestions",
        "com.apple.contacts.postersyncd": "Syncs Contact Poster images across devices",
        "com.apple.contactsd": "Manages the unified contacts database and sync",
        "com.apple.containermanagerd": "Container manager for app sandboxing and data separation",
        "com.apple.containermanagerd.system": "Manages app sandbox containers and data isolation",
        "com.apple.contextstored": "Persists contextual awareness data for system features",
        "com.apple.controlcenter": "Provides Control Center menu bar modules and toggles",
        "com.apple.controlstrip": "Shows the Control Strip on Touch Bar-equipped Macs",
        "com.apple.corebrightnessd": "Controls display brightness, True Tone, and Night Shift",
        "com.apple.corecaptured": "Manages core screen and media capture pipelines",
        "com.apple.coredatad": "Handles Core Data cloud sync and persistent history",
        "com.apple.coreduetd": "Tracks device usage patterns and app interactions for on-device intelligence",
        "com.apple.coreidvd": "Verifies identity documents for Apple ID and Wallet",
        "com.apple.coreimportd": "Indexes file metadata for Spotlight search results",
        "com.apple.corekdld": "Manages kernel extension loading and validation",
        "com.apple.corercd": "Coordinates remote control events from headphones and keyboards",
        "com.apple.corerepaird": "Manages device repair and parts pairing validation",
        "com.apple.coreservices.UASharedPasteboardProgressUI": "Shows Universal Clipboard transfer progress between devices",
        "com.apple.coreservices.appleevents": "Routes Apple Events between applications for automation",
        "com.apple.coreservices.launchservicesd": "Tracks installed apps and handles file-type associations",
        "com.apple.coreservices.sharedfilelistd": "Manages Finder sidebar, recent items, and login items",
        "com.apple.coreservices.uiagent": "Displays system dialogs for file downloads and disk images",
        "com.apple.coreservices.useractivityd": "Coordinates Handoff activity transfer between devices",
        "com.apple.coreservicesd": "Core Services helper — handles app launches, UTI resolution, and file type associations",
        "com.apple.corespeechd": "Handles voice recognition, dictation, and speech processing",
        "com.apple.corespeechd.system": "Provides system-level speech recognition and voice processing",
        "com.apple.corespotlightd": "Indexes content and apps for Spotlight search",
        "com.apple.corespotlightservice": "Processes Spotlight search queries and returns results",
        "com.apple.corestorage.corestoraged": "Manages CoreStorage logical volumes and Fusion Drives",
        "com.apple.corestorage.corestoragehelperd": "Assists with CoreStorage volume conversion and repair",
        "com.apple.coresymbolicationd": "Resolves crash report symbols for readable diagnostics",
        "com.apple.countryd": "Determines device region for locale-specific features",
        "com.apple.csrutil.report": "Reports System Integrity Protection status and violations",
        "com.apple.csuseragent": "Manages user-level core services background tasks",
        "com.apple.ctkbind": "Binds smart card certificates to user accounts for login",
        "com.apple.ctkd": "Manages smart card and cryptographic token operations",
        "com.apple.cvmsCompAgent3425AMD_x86_64": "Compiles GPU shaders for AMD graphics on x86_64",
        "com.apple.cvmsCompAgent3425AMD_x86_64_1": "Compiles GPU shaders for AMD graphics on x86_64 (secondary)",
        "com.apple.cvmsCompAgent3600_arm64": "Compiles GPU shaders for Apple Silicon graphics",
        "com.apple.cvmsCompAgent3600_arm64_1": "Compiles GPU shaders for Apple Silicon graphics (secondary)",
        "com.apple.cvmsCompAgent3600_x86_64": "Compiles GPU shaders for x86_64 graphics pipeline",
        "com.apple.cvmsCompAgent3600_x86_64_1": "Compiles GPU shaders for x86_64 graphics pipeline (secondary)",
        "com.apple.cvmsCompAgent_arm64": "Compiles GPU shader programs for ARM64 architecture",
        "com.apple.cvmsCompAgent_arm64_1": "Compiles additional GPU shaders for ARM64 architecture",
        "com.apple.cvmsCompAgent_x86_64": "Compiles GPU shader programs for x86_64 via Rosetta",
        "com.apple.cvmsCompAgent_x86_64_1": "Compiles GPU shader programs for x86_64 architecture",
        "com.apple.cvmsServ": "Manages compiled GPU shader cache and compilation requests",
        "com.apple.dasd-OSX": "Schedules and prioritizes background system activities",
        "com.apple.dataaccess.dataaccessd": "Syncs calendar, contacts, and mail with remote accounts",
        "com.apple.datastored": "Stores structured data for Siri suggestions and app intents",
        "com.apple.deleted_helper": "Frees disk space by purging deleted and purgeable files",
        "com.apple.devicecheckd": "Validates device integrity for App Store and Apple services",
        "com.apple.devicemanagementclient.managedeventsd": "Processes MDM-triggered events on managed devices",
        "com.apple.devicemanagementclient.teslad": "Handles mobile device management (MDM) profile enforcement",
        "com.apple.devicerecoveryd": "Assists with device recovery and restore operations",
        "com.apple.dhcp6d": "Handles IPv6 network address assignment via DHCPv6",
        "com.apple.diagnosticd": "Diagnostic data collection and reporting",
        "com.apple.diagnosticextensions.osx.spotlight.helper": "Runs Spotlight diagnostics for system troubleshooting",
        "com.apple.diagnosticextensions.osx.timemachine.helper": "Runs Time Machine diagnostics for system troubleshooting",
        "com.apple.diagnosticextensionsd": "Hosts diagnostic extension plug-ins for system reports",
        "com.apple.diagnostics_agent": "Collects diagnostic data when system issues are detected",
        "com.apple.diagnosticservicesd": "Provides diagnostic services for Apple Support sessions",
        "com.apple.diagnosticspushd": "Sends diagnostic reports to Apple when opted in",
        "com.apple.diskarbitrationd": "Disk arbitration — manages disk mounting, unmounting, and volume events",
        "com.apple.diskimagesiod": "Handles mounting and accessing disk image files",
        "com.apple.diskimagesiod.ram": "Manages RAM disk image creation and access",
        "com.apple.diskimagesiod.spb": "Handles sparse bundle disk image operations",
        "com.apple.diskmanagementstartup": "Prepares and verifies disk volumes during system startup",
        "com.apple.diskspaced": "Monitors available disk space and alerts when low",
        "com.apple.displaypolicyd": "Manages display policies including ProMotion refresh rates",
        "com.apple.distnoted.xpc.agent": "Delivers distributed notifications between user apps",
        "com.apple.distnoted.xpc.daemon": "Delivers distributed notifications between system services",
        "com.apple.dmd.agent": "Manages device management data synchronization",
        "com.apple.donotdisturbd": "Manages Focus and Do Not Disturb schedules and rules",
        "com.apple.doubleagentd": "Coordinates cross-device continuity features",
        "com.apple.dprivacyd": "Enforces differential privacy for analytics collection",
        "com.apple.dspluginhelperd": "Loads Directory Services plug-ins for user authentication",
        "com.apple.dt.AutomationModeUI": "Shows UI prompts for enabling Xcode Automation Mode",
        "com.apple.dt.CommandLineTools.installondemand": "Installs Xcode Command Line Tools when requested",
        "com.apple.dt.automationmode-writer": "Enables Automation Mode for UI testing by Xcode",
        "com.apple.dt.fetchsymbolsd": "Downloads debug symbols for system frameworks from Apple",
        "com.apple.dt.previewsd": "Provides live SwiftUI previews for Xcode development",
        "com.apple.dt.previewsviewservice": "Renders SwiftUI preview content for Xcode",
        "com.apple.duetexpertd": "Predicts user activity patterns for proactive system features",
        "com.apple.dvdplayback.setregion": "Manages DVD region code settings for playback",
        "com.apple.dynamic_pager": "Manages virtual memory swap files on disk",
        "com.apple.eapolcfg_auth": "Handles 802.1X network authentication configuration",
        "com.apple.ecosystemagent": "Coordinates features across your Apple devices",
        "com.apple.ecosystemanalyticsd": "Collects anonymized analytics across Apple device ecosystem",
        "com.apple.ecosystemd": "Manages cross-device ecosystem services and handoff",
        "com.apple.efilogin-helper": "Supports pre-boot EFI login for FileVault unlock",
        "com.apple.eligibilityd": "Determines feature eligibility based on region and device",
        "com.apple.email.maild": "Fetches and syncs email messages in the background",
        "com.apple.endpointsecurity.endpointsecurityd": "Provides endpoint security event monitoring for security apps",
        "com.apple.enhancedloggingd": "Enables enhanced system logging when diagnostics are active",
        "com.apple.ensemble": "Coordinates multi-device interactions like Sidecar and Universal Control",
        "com.apple.eoshostd": "Manages embedded OS updates for connected Apple accessories",
        "com.apple.eppc": "Handles remote Apple Events for AppleScript automation",
        "com.apple.erasecontentsettingshelperd": "Supports Erase All Content and Settings functionality",
        "com.apple.exchange.exchangesyncd": "Syncs Exchange email, calendar, and contacts",
        "com.apple.facetimemessagestored": "Stores FaceTime message data and call history",
        "com.apple.fairplayd": "Manages FairPlay DRM for purchased media content",
        "com.apple.fairplaydeviceidentityd": "Manages device identity for FairPlay DRM verification",
        "com.apple.familycircled": "Manages Family Sharing group membership and settings",
        "com.apple.familycontrols": "Enforces Screen Time and parental control restrictions",
        "com.apple.familycontrols.useragent": "Applies Screen Time restrictions for the current user",
        "com.apple.familynotificationd": "Delivers Family Sharing and Screen Time notifications",
        "com.apple.feedbackd": "Submits feedback and bug reports to Apple",
        "com.apple.filesystems.fskitd": "Manages file system extensions and plug-ins",
        "com.apple.filesystems.userfs_helper": "Assists user-space file system implementations",
        "com.apple.filesystems.userfsd": "Runs user-space file system extensions",
        "com.apple.filevaultd": "Manages FileVault full-disk encryption",
        "com.apple.financed": "Handles Apple Pay Later and financing features",
        "com.apple.findmy.findmybeaconingd": "Broadcasts Bluetooth beacons for Find My network",
        "com.apple.findmy.findmylocateagent": "Locates nearby devices using the Find My network",
        "com.apple.findmymac": "Enables Find My Mac location tracking and remote lock",
        "com.apple.findmymacmessenger": "Delivers Find My Mac remote messages and commands",
        "com.apple.firmwaresyncd": "Keeps firmware in sync across internal components",
        "com.apple.followupd": "Manages setup follow-up tasks and reminders",
        "com.apple.fontd.useragent": "Manages font availability and activation for apps",
        "com.apple.fontmover": "Moves and installs font files to system directories",
        "com.apple.frauddefensed": "Detects and prevents fraudulent device activity",
        "com.apple.fseventsd": "File system events daemon — tracks file changes for Time Machine, Spotlight, and apps",
        "com.apple.fskit.fskit_agent": "Manages user-space file system extension lifecycle",
        "com.apple.fskit.fskit_helper": "Provides privileged operations for file system extensions",
        "com.apple.ftp-proxy": "Proxies FTP connections through the application firewall",
        "com.apple.gamed": "Manages Game Center accounts, achievements, and matchmaking",
        "com.apple.gamepolicyd": "Applies system-level game access policies and limits",
        "com.apple.gamesaved": "Syncs Game Center saved game data across devices",
        "com.apple.generativeexperiencesd": "Powers Apple Intelligence generative AI features",
        "com.apple.geoanalyticsd": "Collects anonymized location analytics for Maps improvement",
        "com.apple.geodMachServiceBridge": "Bridges location services between apps and the Maps engine",
        "com.apple.getty": "Manages terminal login prompts on serial and console ports",
        "com.apple.gkreport": "Reports Gatekeeper and app notarization status",
        "com.apple.gputoolsserviced": "Supports GPU debugging and profiling tools for developers",
        "com.apple.griddatad": "Manages energy grid data for clean energy charging",
        "com.apple.gssd": "Handles Kerberos and SPNEGO authentication for network services",
        "com.apple.handwritingd": "Processes handwriting input recognition",
        "com.apple.hdiejectd": "Handles disk image ejection requests",
        "com.apple.helpd": "Indexes and serves Apple Help content for apps",
        "com.apple.hidd": "Human Interface Device daemon — processes keyboard, mouse, and trackpad input",
        "com.apple.historicalaudiod": "Manages historical audio data for sound recognition features",
        "com.apple.homed": "Manages HomeKit devices, scenes, and automations",
        "com.apple.homeenergyd": "Tracks home energy usage data from HomeKit devices",
        "com.apple.homeeventsd": "Processes HomeKit automation triggers and events",
        "com.apple.iCloudNotificationAgent": "Delivers iCloud-related notifications and alerts",
        "com.apple.iCloudUserNotifications": "Shows iCloud storage and account notifications to users",
        "com.apple.icdd": "Discovers and connects to devices via USB and network ICC",
        "com.apple.icloud.findmydeviced": "Manages Find My device tracking through iCloud",
        "com.apple.icloud.findmydeviced.findmydevice-user-agent": "Provides user-level Find My device status and alerts",
        "com.apple.icloud.searchpartyd": "Runs the Find My offline-finding network service",
        "com.apple.icloud.searchpartyuseragent": "Shows Find My item alerts and notifications to users",
        "com.apple.icloudmailagent": "Syncs iCloud Mail in the background",
        "com.apple.iconservices.iconservicesagent": "Generates and caches app and document icons",
        "com.apple.iconservices.iconservicesd": "Caches and serves app and file icons system-wide",
        "com.apple.identityservicesd": "iCloud and Apple ID authentication service",
        "com.apple.idsremoteurlconnectionagent": "Handles remote URL connections for Apple ID services",
        "com.apple.ifdreader": "Reads smart cards via USB smart card reader devices",
        "com.apple.imagent": "Manages iMessage and FaceTime connections and delivery",
        "com.apple.imautomatichistorydeletionagent": "Automatically deletes expired Messages conversation history",
        "com.apple.imklaunchagent": "Launches and manages input method editors for text input",
        "com.apple.imtransferagent": "Handles file transfers sent through iMessage",
        "com.apple.inboxupdaterd": "Updates Mail inbox in the background",
        "com.apple.inputanalyticsd": "Collects anonymized keyboard and input usage analytics",
        "com.apple.installandsetup.migrationhelper.user": "Assists user data migration from another Mac or backup",
        "com.apple.installandsetup.systemmigrationd": "Handles system-level data migration during Mac setup",
        "com.apple.installcoordination_proxy": "Proxies app installation requests between processes",
        "com.apple.installcoordinationd": "Coordinates app installs, updates, and deletions",
        "com.apple.installd": "App installation daemon",
        "com.apple.installd.user": "Installs and manages per-user app bundles",
        "com.apple.installerauthagent": "Shows authentication prompts during software installation",
        "com.apple.intelligencecontextd": "Provides contextual data for Apple Intelligence features",
        "com.apple.intelligenceflowd": "Orchestrates Apple Intelligence processing workflows",
        "com.apple.intelligenceplatformd": "Runs the core Apple Intelligence on-device AI platform",
        "com.apple.intelligencetasksd": "Schedules and runs Apple Intelligence background tasks",
        "com.apple.intelligentroutingd": "Routes requests between on-device and cloud AI processing",
        "com.apple.iomfb_bics_daemon": "Manages display framebuffer initialization and calibration",
        "com.apple.iomfb_fdr_loader": "Loads display factory calibration data",
        "com.apple.ionodecache": "Caches I/O device tree node information",
        "com.apple.ioupsd": "Monitors UPS battery status and manages power events",
        "com.apple.itunescloudd": "Syncs iTunes and Apple Music library with iCloud",
        "com.apple.jetpackassetd": "Manages asset downloads for system AI model updates",
        "com.apple.jetsamproperties.Mac": "Configures memory pressure limits for running processes",
        "com.apple.kcgend": "Generates and manages Keychain encryption keys",
        "com.apple.kcproxy": "Proxies Keychain access requests between processes",
        "com.apple.kdumpd": "Captures kernel crash dumps over the network",
        "com.apple.kernelmanager_helper": "Assists with kernel extension loading and management",
        "com.apple.kernelmanagerd": "Loads and validates kernel extensions and system extensions",
        "com.apple.keyboardservicesd": "Manages keyboard settings, layouts, and input sources",
        "com.apple.keychainsharingmessagingd": "Shares Keychain items securely between your Apple devices",
        "com.apple.knowledge-agent": "Tracks app usage and context for Siri Suggestions",
        "com.apple.knowledgeconstructiond": "Builds on-device knowledge graph for intelligent features",
        "com.apple.kuncd": "Displays kernel user notification dialogs and alerts",
        "com.apple.languageassetd": "Downloads language packs and localization resources on demand",
        "com.apple.lightsoutmanagementd": "Enables remote management of Mac when powered off or sleeping",
        "com.apple.linkd": "Manages deep links and universal link associations",
        "com.apple.liquiddetectiond": "Detects liquid exposure on supported hardware ports",
        "com.apple.liveactivitiesd": "Manages Live Activities on Mac from iPhone apps",
        "com.apple.localizationswitcherd": "Handles language and locale switching at runtime",
        "com.apple.locate": "Builds the locate database for fast file searching",
        "com.apple.locationaccessstored": "Stores app location access history and permissions",
        "com.apple.locationd": "Location Services daemon — provides GPS/Wi-Fi/cellular location to apps",
        "com.apple.lockd": "Provides NFS file locking for network file sharing",
        "com.apple.lockdownmoded": "Enforces Lockdown Mode security restrictions when enabled",
        "com.apple.lockoutagent": "Shows the screen lock and password entry interface",
        "com.apple.logd": "Unified logging daemon — collects and stores system/app log entries",
        "com.apple.logd_helper": "Assists the unified logging system with log storage",
        "com.apple.logd_reporter": "Sends collected log data for crash and diagnostic reports",
        "com.apple.logind": "Handles user login authentication and session creation",
        "com.apple.loginwindow": "Manages the login screen and user session lifecycle",
        "com.apple.loginwindow.LWWeeklyMessageTracer": "Collects weekly login window usage diagnostics",
        "com.apple.logkextloadsd": "Logs kernel extension loading events for diagnostics",
        "com.apple.lsd": "Launch Services daemon — maintains the app database and file associations",
        "com.apple.lskdd": "Maintains the Launch Services database of registered apps",
        "com.apple.mDNSResponder": "Bonjour/DNS-SD — handles local network discovery and DNS resolution",
        "com.apple.mDNSResponderHelper": "Assists Bonjour with privileged network service discovery operations",
        "com.apple.macos.studentd": "Supports Classroom app features for student devices",
        "com.apple.managedappdistributionagent": "Handles managed app installation for enterprise devices",
        "com.apple.managedappdistributiond": "Distributes managed apps configured by MDM profiles",
        "com.apple.managedcorespotlightd": "Manages Spotlight indexing policies for enterprise-managed devices",
        "com.apple.maps.destinationd": "Provides destination suggestions and arrival estimates for Maps",
        "com.apple.mbbackgrounduseragent": "Handles background tasks for Mac-to-iOS device pairing",
        "com.apple.mbfloagent": "Supports Find My and location features for paired devices",
        "com.apple.mbproximityhelper": "Detects nearby Apple devices for Handoff and continuity",
        "com.apple.mbsystemadministration": "Manages system-level mobile device pairing configuration",
        "com.apple.mbuseragent": "Handles user-level communication with paired mobile devices",
        "com.apple.mbusertrampoline": "Launches user-level processes for mobile device integration",
        "com.apple.mdmclient.agent": "Communicates with your MDM server for device management",
        "com.apple.mdmclient.daemon": "Processes mobile device management commands from your organization",
        "com.apple.mdmclient.daemon.runatboot": "Applies MDM policies immediately at system boot",
        "com.apple.mdworker.mail": "Indexes Mail messages for Spotlight search",
        "com.apple.mdworker.shared": "Indexes files for Spotlight search across applications",
        "com.apple.mdworker.single.arm64": "Runs Spotlight indexing plugins natively on Apple Silicon",
        "com.apple.mdworker.single.x86_64": "Runs Spotlight indexing plugins translated for Intel compatibility",
        "com.apple.mdworker.sizing": "Calculates file and folder sizes for Spotlight metadata",
        "com.apple.mediaanalysisd": "Analyzes photos and videos for face recognition and scene detection",
        "com.apple.mediacontinuityd": "Enables Continuity Camera and media streaming between devices",
        "com.apple.mediaremoteagent": "Handles media playback remote control between apps and devices",
        "com.apple.mediaremoted": "Media remote daemon — handles Now Playing and media key events",
        "com.apple.mediastream.mstreamd": "Manages Photo Stream uploads and downloads via iCloud",
        "com.apple.memory-maintenance": "Performs periodic memory cleanup and compaction tasks",
        "com.apple.menuextra.battery.helper": "Provides battery status information for the menu bar",
        "com.apple.metadata.mdbulkimport": "Performs bulk Spotlight indexing of large file sets",
        "com.apple.metadata.mdflagwriter": "Writes Spotlight metadata flags to track indexing state",
        "com.apple.metadata.mds": "Metadata server — indexes files for Spotlight search",
        "com.apple.metadata.mds.index": "Manages the core Spotlight search index database",
        "com.apple.metadata.mds.index.readonly": "Serves read-only Spotlight search queries from the index",
        "com.apple.metadata.mds.scan": "Scans directories to find new files for Spotlight indexing",
        "com.apple.metadata.mds.spindump": "Captures Spotlight performance diagnostics when indexing stalls",
        "com.apple.metadata.mdwrite": "Writes updated metadata attributes to the Spotlight index",
        "com.apple.metrickitd": "Collects app and system performance metrics for diagnostics",
        "com.apple.midiserver": "Routes MIDI messages between music apps and audio devices",
        "com.apple.milod": "Manages on-device machine learning model delivery and updates",
        "com.apple.misagent": "Manages installed provisioning profiles for enterprise apps",
        "com.apple.mlhostd": "Hosts machine learning model inference in a sandboxed process",
        "com.apple.mlruntimed": "Manages on-device machine learning model execution scheduling",
        "com.apple.mobile.NRDUpdated": "Updates network relay configuration for connected devices",
        "com.apple.mobile.keybagd": "Manages encryption keys for Data Protection and secure storage",
        "com.apple.mobile.notification_proxy": "Relays notifications between macOS and connected iOS devices",
        "com.apple.mobile.obliteration": "Handles secure data erasure for device reset operations",
        "com.apple.mobile.softwareupdated": "Manages software update checks and installations for connected devices",
        "com.apple.mobile.storage_mounter": "Mounts disk images and developer resources on connected devices",
        "com.apple.mobile.storage_mounter_proxy": "Proxies storage mounting requests to connected mobile devices",
        "com.apple.mobile.usermanagerd": "Manages user accounts on connected mobile devices",
        "com.apple.mobileactivationd": "Handles device activation and identity verification with Apple",
        "com.apple.mobileassetd": "Downloads and manages Apple software assets and updates",
        "com.apple.mobilegestalt.xpc": "Provides device hardware and configuration information to apps",
        "com.apple.mobilerepaird": "Supports diagnostics and repair workflows for Apple devices",
        "com.apple.mobiletimerd": "Synchronizes clocks between Mac and connected mobile devices",
        "com.apple.modelcatalogd": "Manages the catalog of available on-device machine learning models",
        "com.apple.modelmanagerd": "Downloads and manages on-device machine learning model assets",
        "com.apple.msrpc.echosvc": "Provides SMB echo service for Windows file sharing compatibility",
        "com.apple.msrpc.lsarpc": "Handles SMB security policy lookups for Windows interoperability",
        "com.apple.msrpc.mdssvc": "Provides Spotlight search over SMB shared folders",
        "com.apple.msrpc.netlogon": "Handles SMB network authentication for Windows domain access",
        "com.apple.msrpc.srvsvc": "Manages SMB file server information for Windows clients",
        "com.apple.msrpc.wkssvc": "Provides SMB workstation service for Windows network browsing",
        "com.apple.multiversed": "Manages multiple runtime environments for app compatibility",
        "com.apple.musicd": "Manages Apple Music library, playback, and sync operations",
        "com.apple.nand.aspcarry": "Performs NAND flash storage health and wear-leveling operations",
        "com.apple.nand_task_scheduler": "Schedules background NAND flash storage maintenance tasks",
        "com.apple.naturallanguaged": "Provides natural language processing for text analysis features",
        "com.apple.navd": "Provides turn-by-turn navigation data for Maps directions",
        "com.apple.ndoagent": "Manages notification delivery optimization for apps",
        "com.apple.neagent": "Handles Network Extension VPN and content filter authentication",
        "com.apple.nearbyd": "Manages nearby device discovery for AirDrop and Handoff",
        "com.apple.nehelper": "Provides network extension configuration and policy evaluation",
        "com.apple.nesessionmanager": "Network Extension session manager (VPN, content filters)",
        "com.apple.netauth.sys.auth": "Handles system-level network authentication for directory services",
        "com.apple.netauth.sys.gui": "Shows system-level network login dialog prompts",
        "com.apple.netauth.user.auth": "Handles user-level network share authentication",
        "com.apple.netauth.user.gui": "Shows user-level network login dialog prompts",
        "com.apple.netbiosd": "Provides NetBIOS name resolution for Windows network browsing",
        "com.apple.networkserviceproxy-osx": "Proxies network traffic for Private Relay and secure connections",
        "com.apple.newsd": "Manages Apple News content delivery and personalization",
        "com.apple.newsyslog": "Rotates and compresses system log files on a schedule",
        "com.apple.nexusd": "Coordinates device-to-device communication for Continuity features",
        "com.apple.nfcd": "Manages NFC and Express Card interactions on supported Macs",
        "com.apple.nfsconf": "Applies NFS client and server configuration at startup",
        "com.apple.nfsd": "Provides Network File System server for file sharing",
        "com.apple.notes.exchangenotesd": "Syncs Notes with Microsoft Exchange accounts",
        "com.apple.noticeboard.agent": "Displays system notification banners and widgets",
        "com.apple.noticeboard.state": "Tracks notification and widget display state",
        "com.apple.notificationcenterui": "Renders the Notification Center interface and widgets",
        "com.apple.notifyd": "Distributed notification center — routes inter-process notifications",
        "com.apple.nsurlsessiond": "Background URL session daemon — handles app background downloads",
        "com.apple.oahd": "Translates Intel apps to run on Apple Silicon via Rosetta",
        "com.apple.oahd-root-helper": "Performs privileged Rosetta translation and installation tasks",
        "com.apple.ocspd": "Validates SSL certificate revocation status for secure connections",
        "com.apple.odproxyd": "Proxies Open Directory requests to remote directory servers",
        "com.apple.online-authd.xpc": "Handles online authentication for Apple ID and cloud services",
        "com.apple.opendirectoryd": "Open Directory — handles user authentication and directory services",
        "com.apple.osanalytics.osanalyticshelper": "Operating system analytics helper",
        "com.apple.ospredictiond": "Predicts operating system usage patterns for proactive features",
        "com.apple.parentalcontrols.check": "Evaluates and enforces parental control restrictions",
        "com.apple.parsec-fbf": "Processes Siri and search suggestions with federated learning",
        "com.apple.parsecd": "Powers Siri Suggestions, Spotlight, and Look Up results",
        "com.apple.passd": "Manages Apple Wallet passes, cards, and payment tokens",
        "com.apple.pboard": "Provides the system pasteboard (clipboard) for copy/paste",
        "com.apple.pbs": "Manages the pasteboard (clipboard) and app service menus",
        "com.apple.pcapd": "Captures network packets from connected iOS devices for debugging",
        "com.apple.peakpowermanagerd": "Manages CPU and GPU peak power delivery and throttling",
        "com.apple.peopled": "Manages contact suggestions and people identification across apps",
        "com.apple.perfpowermetricd": "Collects CPU and GPU performance and energy metrics",
        "com.apple.pfctl": "Loads packet filter firewall rules at system startup",
        "com.apple.pfd": "Manages persistent packet filter firewall state and logging",
        "com.apple.photoanalysisd": "Analyzes photos for People, Places, Memories, and search features",
        "com.apple.photolibraryd": "Manages the Photos library database and iCloud Photo sync",
        "com.apple.pluginkit.pkd": "Manages discovery and lifecycle of app extensions",
        "com.apple.pluginkit.pkreporter": "Reports app extension usage statistics for diagnostics",
        "com.apple.postfix.master": "Runs the Postfix mail transfer server for sending email",
        "com.apple.postfix.newaliases": "Rebuilds the Postfix email alias database",
        "com.apple.postupgraded": "Performs cleanup and migration tasks after macOS upgrades",
        "com.apple.powerchime": "Plays the charging sound when connecting to power",
        "com.apple.powerd": "Power management daemon — handles sleep, wake, battery, and thermal events",
        "com.apple.powerd.swd": "Monitors power management and logs sleep/wake diagnostics",
        "com.apple.powerdatad": "Collects battery and power usage data for energy reports",
        "com.apple.powerexperienced": "Optimizes charging patterns to preserve battery health",
        "com.apple.powerlogHelperd": "Records detailed power and battery usage logs for diagnostics",
        "com.apple.preference.displays.MirrorDisplays": "Handles display mirroring configuration from System Settings",
        "com.apple.preferences.timezone.admintool": "Manages time zone settings with admin privileges",
        "com.apple.previewshellapp": "Provides Quick Look preview rendering for files",
        "com.apple.printtool.agent": "Manages user-level print job submission and queue display",
        "com.apple.printtool.daemon": "Handles privileged printing operations and printer management",
        "com.apple.printuitool.agent": "Displays print dialog UI and printer selection interface",
        "com.apple.privatecloudcomputed": "Processes Private Cloud Compute requests for Apple Intelligence",
        "com.apple.prngseedd": "Seeds the system cryptographic random number generator",
        "com.apple.proactived": "Powers proactive Siri Suggestions and intelligent recommendations",
        "com.apple.proactiveeventtrackerd": "Tracks events to improve proactive Siri Suggestions accuracy",
        "com.apple.progressd": "Tracks and displays progress for system setup and migration",
        "com.apple.protectedcloudstorage.protectedcloudkeysyncing": "Syncs encrypted Keychain data securely across your iCloud devices",
        "com.apple.ptpcamerad": "Manages connections to PTP/USB digital cameras for photo import",
        "com.apple.quicklook": "Generates file previews for Quick Look in Finder",
        "com.apple.quicklook.ThumbnailsAgent": "Creates thumbnail images for files displayed in Finder",
        "com.apple.quicklook.ui.helper": "Renders the Quick Look preview window interface",
        "com.apple.racoon": "Manages IPSec VPN connections and key exchange",
        "com.apple.rapportd": "Enables Continuity features like Handoff and Universal Clipboard",
        "com.apple.rapportd-user": "Enables wireless communication with nearby Apple devices",
        "com.apple.rcd": "Handles media key events for playback control in apps",
        "com.apple.recentsd": "Tracks recently opened files and apps for quick access",
        "com.apple.relatived": "Manages family and relationship data for Contacts features",
        "com.apple.remindd": "Manages Reminders data, sync, and notification scheduling",
        "com.apple.remotecompositorclientd": "Renders UI compositing for remote display sessions",
        "com.apple.remoted": "Handles communication with remote Apple devices and accessories",
        "com.apple.remotemanagementd": "Processes remote device management commands and declarations",
        "com.apple.remotepairtool": "Pairs with remote Apple devices for development and diagnostics",
        "com.apple.replayd": "Records screen activity for Game Center replays and clips",
        "com.apple.replicatord": "Replicates managed content and data across enrolled devices",
        "com.apple.retimerd": "Manages Thunderbolt and USB-C retimer chip firmware updates",
        "com.apple.reversetemplated": "Generates reverse templates for data detection in text",
        "com.apple.revisiond": "Manages document revision snapshots (Versions feature)",
        "com.apple.routined": "Learns location patterns to predict frequent destinations",
        "com.apple.rpcbind": "Maps RPC program numbers to network ports for NFS",
        "com.apple.rtcreportingd": "Reports real-time communication quality metrics for FaceTime",
        "com.apple.runningboardd": "RunningBoard — manages app lifecycle, activation, and resource limits",
        "com.apple.sandboxd": "App Sandbox enforcement daemon",
        "com.apple.scopedbookmarkagent.xpc": "Manages security-scoped file access bookmarks for sandboxed apps",
        "com.apple.screencaptureui": "Provides the screenshot and screen recording toolbar interface",
        "com.apple.screensharing": "Allows remote users to view and control your Mac screen",
        "com.apple.screensharing.MessagesAgent": "Enables screen sharing invitations through the Messages app",
        "com.apple.screensharing.agent": "Manages screen sharing sessions for the current user",
        "com.apple.screensharing.menuextra": "Displays the screen sharing status icon in the menu bar",
        "com.apple.scrod": "Manages scheduled system maintenance scripts",
        "com.apple.scsid": "Handles smart card services and authentication",
        "com.apple.searchtoold": "Provides search suggestions and indexing support for Spotlight",
        "com.apple.secd": "Manages keychain items, keys, and secure credentials",
        "com.apple.secinitd": "Initializes and enforces app security policies at launch",
        "com.apple.securemessagingagent": "Manages secure messaging encryption and key exchange",
        "com.apple.security.DiskUnmountWatcher": "Monitors disk unmount events for security enforcement",
        "com.apple.security.FDERecoveryAgent": "Manages FileVault recovery key escrow and retrieval",
        "com.apple.security.KeychainStasher": "Caches keychain credentials for use during login",
        "com.apple.security.agent": "Displays authorization dialogs for password and permission prompts",
        "com.apple.security.agent.login": "Handles security authorization prompts at the login window",
        "com.apple.security.authhost": "Hosts plug-ins that perform authorization checks",
        "com.apple.security.authtrampoline": "Executes privileged tools after authorization approval",
        "com.apple.security.cloudkeychainproxy3": "Syncs keychain data securely across devices via iCloud",
        "com.apple.security.cryptexd": "Manages cryptographically sealed OS extension volumes",
        "com.apple.security.keychain-circle-notification": "Notifies when iCloud Keychain trust circle changes occur",
        "com.apple.security.syspolicy": "Enforces Gatekeeper and system security policies for apps",
        "com.apple.security.xprotectd": "Scans for and blocks known malware using XProtect definitions",
        "com.apple.securityd": "Security daemon — manages keychain access, code signing, and trust evaluation",
        "com.apple.securityd.system": "Provides system-level cryptographic and certificate services",
        "com.apple.securityuploadd": "Uploads security diagnostics and analytics to Apple",
        "com.apple.seld": "Manages Secure Enclave operations and data protection",
        "com.apple.seserviced": "Handles Secure Element operations for Apple Pay and NFC",
        "com.apple.sessionlogoutd": "Performs cleanup tasks when a user session logs out",
        "com.apple.sharingd": "Provides AirDrop, Shared Albums, and nearby sharing services",
        "com.apple.shazamd": "Provides music recognition services for Shazam integration",
        "com.apple.sidecar-hid-relay": "Relays touch and Pencil input from iPad in Sidecar mode",
        "com.apple.sidecar-relay": "Manages the display connection for Sidecar with iPad",
        "com.apple.signpost.signpost_reporter": "Collects and reports performance signpost data for diagnostics",
        "com.apple.siriactionsd": "Processes and executes Siri Shortcuts and actions",
        "com.apple.siriinferenced": "Provides on-device intelligence and suggestions for Siri",
        "com.apple.siriknowledged": "Manages Siri knowledge base and contextual information",
        "com.apple.sirittsd": "Provides text-to-speech synthesis for Siri voice output",
        "com.apple.smb.preferences": "Manages SMB file sharing configuration preferences",
        "com.apple.smbd": "Provides Windows-compatible SMB file sharing services",
        "com.apple.sntpd": "Synchronizes system clock with network time servers",
        "com.apple.sociallayerd": "Manages social media account integrations and sharing",
        "com.apple.softwareupdate_firstrun_tasks": "Runs initial setup tasks after a macOS software update",
        "com.apple.softwareupdated": "Software Update daemon — checks for and installs macOS updates",
        "com.apple.speech.speechdatainstallerd": "Downloads and installs speech recognition language data",
        "com.apple.speech.speechsynthesisd.arm64": "Provides text-to-speech synthesis on Apple Silicon Macs",
        "com.apple.speech.speechsynthesisd.x86_64": "Provides text-to-speech synthesis on Intel Macs",
        "com.apple.speech.synthesisserver": "Hosts the system-wide speech synthesis engine",
        "com.apple.spindump": "Hang detection — captures stack samples from unresponsive apps",
        "com.apple.spindump_agent": "Captures hang and spin reports for unresponsive applications",
        "com.apple.sportsd": "Provides live sports scores and updates for system apps",
        "com.apple.spotlightknowledged": "Manages Spotlight knowledge and Siri suggestion data",
        "com.apple.spotlightknowledged.importer": "Imports app usage and content data into Spotlight knowledge",
        "com.apple.spotlightknowledged.updater": "Updates Spotlight knowledge index with new information",
        "com.apple.srp-mdns-proxy": "Proxies mDNS service registration for Thread network devices",
        "com.apple.startupdiskhelper": "Assists with startup disk selection and boot configuration",
        "com.apple.statd.notify": "Handles NFS file lock status notifications",
        "com.apple.stickersd": "Manages sticker packs and Memoji for Messages",
        "com.apple.storagekitd": "Manages disk partitioning, APFS volumes, and storage operations",
        "com.apple.storeaccountd": "Manages Apple ID and App Store account authentication",
        "com.apple.storeassetd": "Downloads and manages App Store asset resources",
        "com.apple.storedownloadd": "Handles App Store and software update downloads",
        "com.apple.storekitagent": "Processes in-app purchases and StoreKit transactions",
        "com.apple.storelegacy": "Provides backward compatibility for older App Store operations",
        "com.apple.storereceiptinstaller": "Verifies and installs App Store purchase receipts",
        "com.apple.storeuid": "Displays App Store authentication and purchase dialogs",
        "com.apple.suggestd": "Extracts contacts, events, and entities from content for suggestions",
        "com.apple.suhelperd": "Performs privileged software update installation tasks",
        "com.apple.swcd": "Manages shared web credentials and app-website associations",
        "com.apple.swiftuitraced": "Collects SwiftUI performance traces for developer diagnostics",
        "com.apple.swtransparencyd": "Verifies software transparency logs for code integrity",
        "com.apple.symptomsd": "Network diagnostics — monitors connection quality and reports issues",
        "com.apple.symptomsd-diag": "Collects network diagnostics when connectivity issues are detected",
        "com.apple.symptomsd.distributed-agent": "Monitors network quality and reports connectivity symptoms",
        "com.apple.synapse.contentlinkingd": "Links related content across apps using on-device intelligence",
        "com.apple.syncdefaultsd": "Synchronizes user preference defaults across devices via iCloud",
        "com.apple.syncservices.SyncServer": "Manages data synchronization between apps and sync stores",
        "com.apple.syncservices.uihandler": "Displays sync conflict resolution UI to the user",
        "com.apple.sysdiagnose": "Collects comprehensive system diagnostics on demand",
        "com.apple.sysdiagnose.darwinos": "Gathers low-level OS diagnostic information for sysdiagnose",
        "com.apple.sysdiagnose_agent": "Collects comprehensive system diagnostic reports on demand",
        "com.apple.sysdiagnose_helper": "Performs privileged system diagnostic data collection",
        "com.apple.sysextd": "Manages installation and lifecycle of system extensions",
        "com.apple.syslogd": "Legacy syslog daemon (unified logging preferred)",
        "com.apple.sysmond": "Monitors system resource usage and performance metrics",
        "com.apple.system_installd": "Handles system-level software and package installation",
        "com.apple.systemkeychain": "Manages the system-wide keychain for shared credentials",
        "com.apple.systemprofiler": "Gathers hardware and software information for System Report",
        "com.apple.systemsettingsagent": "Supports background operations for System Settings",
        "com.apple.systemstats.analysis": "Analyzes collected system performance statistics",
        "com.apple.systemstats.daily": "Runs daily system performance data collection tasks",
        "com.apple.systemstats.microstackshot_periodic": "Periodically samples process stacks for performance analysis",
        "com.apple.systemstatusd": "Tracks and reports overall system health status",
        "com.apple.tailspind": "Continuous stack sampling for performance analysis",
        "com.apple.talagent": "Manages Transparency, Consent, and Control policy prompts",
        "com.apple.taskgated": "Validates code signatures before allowing task access",
        "com.apple.taskgated-helper": "Validates code signatures for privileged task operations",
        "com.apple.tccd": "Transparency, Consent, Control — manages privacy permissions (camera, mic, disk, etc.)",
        "com.apple.tccd.system": "Enforces system-level privacy and data access permissions",
        "com.apple.telephonyutilities.callservicesd": "Manages FaceTime and iPhone call relay on your Mac",
        "com.apple.testmanagerd": "Coordinates XCTest execution for developer testing workflows",
        "com.apple.textcomposerd": "Processes text composition for input method editors",
        "com.apple.textunderstandingd": "Provides on-device text analysis and entity recognition",
        "com.apple.thermald": "Manages thermal throttling to prevent hardware overheating",
        "com.apple.thermalmonitord": "Thermal monitoring — throttles performance to prevent overheating",
        "com.apple.thermaltrap": "Monitors thermal sensors and triggers protective actions",
        "com.apple.threadradiod": "Controls the Thread radio for smart home networking",
        "com.apple.timed": "Time daemon — manages NTP sync, timezone, and system clock",
        "com.apple.timesync.audioclocksyncd": "Synchronizes audio clocks for precise multi-device playback",
        "com.apple.timezoneupdates.tzd": "Updates time zone data based on location changes",
        "com.apple.timezoneupdates.tznotify": "Notifies apps when the system time zone changes",
        "com.apple.tipsd": "Delivers helpful Tips notifications about macOS features",
        "com.apple.tmp_cleaner": "Periodically removes old temporary files to free disk space",
        "com.apple.touchbarserver": "Manages Touch Bar content and app interactions",
        "com.apple.tracd": "Handles Transparency Resource Access Consent logging",
        "com.apple.translationd": "Provides on-device text and speech translation services",
        "com.apple.transparencyStaticKey": "Manages static transparency keys for system integrity checks",
        "com.apple.transparencyd": "Verifies macOS system component integrity via Apple OS Transparency",
        "com.apple.triald": "Manages on-device ML experiments for Siri and system intelligence",
        "com.apple.triald.system": "Manages system-level A/B feature experiments and rollouts",
        "com.apple.trustd": "Evaluates certificate trust for code signing and TLS connections",
        "com.apple.trustd.agent": "Evaluates certificate trust and revocation for the user",
        "com.apple.trustdFileHelper": "Reads and manages certificate trust settings files",
        "com.apple.tzlinkd": "Manages time zone link data and geolocation updates",
        "com.apple.uarpassetmanagerd": "Manages firmware assets for USB accessory updates",
        "com.apple.uarpd": "Coordinates firmware updates for connected USB accessories",
        "com.apple.uarphidd": "Handles HID device firmware updates via UARP protocol",
        "com.apple.uarppersonalizationd": "Personalizes accessory firmware during the update process",
        "com.apple.ucupdate": "Updates Unicode support data and character databases",
        "com.apple.uikitsystemapp": "Hosts UIKit-based system interface components on macOS",
        "com.apple.uninstalld": "Handles app uninstallation and cleanup of removed software",
        "com.apple.universalaccessAuthWarn": "Warns about apps requesting accessibility permissions",
        "com.apple.universalaccesscontrol": "Manages accessibility feature activation and control",
        "com.apple.universalaccessd": "Accessibility services daemon",
        "com.apple.unmountassistant.sysagent": "Assists with safe disk ejection at the system level",
        "com.apple.unmountassistant.useragent": "Helps safely eject disks and shows unmount progress",
        "com.apple.usbaudiod": "Manages audio input and output for USB audio devices",
        "com.apple.usbctelemetryd": "Collects USB-C connection diagnostics and telemetry data",
        "com.apple.usbnotificationagent": "Displays notifications about USB device connections and issues",
        "com.apple.usbpowerd": "Manages power delivery for connected USB devices",
        "com.apple.usbsmartcardreaderd": "Provides smart card reader support over USB connections",
        "com.apple.usermanagerhelper": "Assists with user account creation and management tasks",
        "com.apple.usernoted": "User notification daemon — delivers app notifications to Notification Center",
        "com.apple.usernotificationsd": "Coordinates delivery of user-facing notifications system-wide",
        "com.apple.uucp": "Provides legacy Unix-to-Unix copy protocol file transfer",
        "com.apple.videosubscriptionsd": "Manages video streaming service subscriptions and authentication",
        "com.apple.voicebankingd": "Records and processes voice samples for Personal Voice",
        "com.apple.voicememod": "Voice Memo recording daemon",
        "com.apple.vsdbutil": "Manages volume status database for disk permission tracking",
        "com.apple.wallpaper": "Manages desktop wallpaper display and dynamic updates",
        "com.apple.wallpaper.export": "Exports wallpaper data for sharing or display purposes",
        "com.apple.warmd": "App warmup daemon — preloads frequently used apps for faster launch",
        "com.apple.warmd_agent": "Pre-warms apps and caches to speed up launch times",
        "com.apple.watchdogd": "Monitors critical system services and restarts them if they hang",
        "com.apple.watchlistd": "Tracks your movie and TV show watchlist across Apple apps",
        "com.apple.weatherd": "Fetches and caches weather data for Weather and widgets",
        "com.apple.webinspectord": "Enables Safari Web Inspector for remote webpage debugging",
        "com.apple.webkit.webpushd": "Delivers web push notifications from Safari websites",
        "com.apple.webprivacyd": "Enforces Intelligent Tracking Prevention and web privacy rules",
        "com.apple.wifi.WiFiAgent": "Manages Wi-Fi connections and displays the menu bar icon",
        "com.apple.wifiFirmwareLoader": "Loads firmware updates for the Wi-Fi hardware module",
        "com.apple.wifianalyticsd": "Collects Wi-Fi performance analytics to improve connectivity",
        "com.apple.wifip2pd": "Wi-Fi peer-to-peer daemon (AirDrop, AirPlay)",
        "com.apple.wifivelocityd": "Measures Wi-Fi network speed and connection quality",
        "com.apple.xartstorageremoted": "Manages secure xART storage for remote device pairing",
        "com.apple.xpc.loginitemregisterd": "Registers and manages login items that launch at startup",
        "com.apple.xpc.otherbsd": "Hosts miscellaneous BSD system services via XPC",
        "com.apple.xpc.roleaccountd": "Manages role-based user accounts for system services",
        "com.apple.xpc.smd": "Manages XPC service lifecycle and on-demand launching",
        "com.apple.xpc.uscwoap": "Handles XPC user-space connection watchdog operations",
        "com.apple.xsan": "Provides Xsan clustered storage area network file system support",
        "com.apple.xscertadmin": "Administers Xsan certificate management operations",
        "com.apple.xscertd": "Manages certificates for Xsan storage network authentication",
        "com.apple.xscertd-helper": "Performs privileged Xsan certificate management tasks",
        "com.openssh.ssh-agent": "Caches SSH private keys for passwordless remote authentication",
        "com.vix.cron": "Runs scheduled tasks using the classic Unix cron scheduler",
        "ntalk": "Provides the legacy Unix network talk chat service",
        "org.apache.httpd": "Serves websites using the built-in Apache HTTP web server",
        "org.cups.cups-lpd": "Accepts print jobs via the legacy LPD printing protocol",
        "org.cups.cupsd": "Manages printers and processes print jobs via CUPS",
        "org.net-snmp.snmpd": "Provides network device monitoring via SNMP protocol",
        "org.openldap.slapd": "Runs an OpenLDAP directory server for user lookups",
        "ssh": "Allows remote users to securely log in via SSH",
        "tftp": "Serves files using the Trivial File Transfer Protocol",
    ]
}
